export const ADD_TO_CART = 'ADD_TO_CART'
export const CHECKOUT_REQUEST = 'CHECKOUT_REQUEST'
export const CHECKOUT_SUCCESS = 'CHECKOUT_SUCCESS'
export const CHECKOUT_FAILURE = 'CHECKOUT_FAILURE'
export const RECEIVE_PRODUCTS = 'RECEIVE_PRODUCTS'



export const SHOWLOADING = 'SHOWLOADING'
export const HIDELOADING = 'HIDELOADING'
export const CHANGESEARCHBAR = 'CHANGESEARCHBAR'
export const SHOWSEARCHBAR = 'SHOWSEARCHBAR';//显示搜索页输入框
export const CLEARSEARCHHISTORY = 'CLEARSEARCHHISTORY';//清除搜索记录
export const ADDSEARCHHISTORY = 'ADDSEARCHHISTORY';//add搜索记录
export const CHOOSEREMARKRADIOS = 'CHOOSEREMARKRADIOS';//记录选择的标签

export const HIDENAVBAR = 'HIDENAVBAR';//微信下隐藏导航栏
